# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.name = QtWidgets.QLabel(Form)
        self.name.setGeometry(QtCore.QRect(140, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.IDnumber = QtWidgets.QLabel(Form)
        self.IDnumber.setGeometry(QtCore.QRect(390, 230, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.IDnumber.setFont(font)
        self.IDnumber.setObjectName("IDnumber")
        self.NameEdit = QtWidgets.QLineEdit(Form)
        self.NameEdit.setGeometry(QtCore.QRect(210, 230, 141, 41))
        self.NameEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.NameEdit.setText("")
        self.NameEdit.setObjectName("NameEdit")
        self.IDEdit = QtWidgets.QLineEdit(Form)
        self.IDEdit.setGeometry(QtCore.QRect(510, 230, 141, 41))
        self.IDEdit.setObjectName("IDEdit")
        self.topic = QtWidgets.QLabel(Form)
        self.topic.setGeometry(QtCore.QRect(120, 80, 571, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.topic.setFont(font)
        self.topic.setObjectName("topic")
        self.login = QtWidgets.QPushButton(Form)
        self.login.setGeometry(QtCore.QRect(500, 320, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.login_output = QtWidgets.QLabel(Form)
        self.login_output.setGeometry(QtCore.QRect(590, 180, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.login_output.setFont(font)
        self.login_output.setText("")
        self.login_output.setObjectName("login_output")
        self.commit = QtWidgets.QPushButton(Form)
        self.commit.setGeometry(QtCore.QRect(180, 320, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.commit.setFont(font)
        self.commit.setObjectName("commit")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 320, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name.setText(_translate("Form", "Name"))
        self.IDnumber.setText(_translate("Form", "IDNumber"))
        self.topic.setText(_translate("Form", "student information database"))
        self.login.setText(_translate("Form", "login"))
        self.commit.setText(_translate("Form", "注册档案"))
        self.pushButton_2.setText(_translate("Form", "查询档案"))
